services:
  mongo: # Database
    container_name: mongodb
    networks:
      - registrador-app-network
    image: mongo
    volumes:
      - ./db_data:/data/db
    restart: always # Always restart the container even if it is manually stoped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - 1234:1234

  mongo-express: # Administration interface for MongoDB
    container_name: mongo-express
    networks:
      - registrador-app-network
    image: mongo-express
    links:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    container_name: app
    networks:
      - registrador-app-network
    build: .
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/
      TZ: America/Sao_Paulo # Set timezone to Sao Paulo - package 'time' will look for this env variable
    #command: tail -F anything
    command: air

networks:
  registrador-app-network:
    name: registrador-app-network